const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    GOOGLE_SINGIN_START: 'GOOGLE_SIGN_IN_START',
    EMAIL_SINGIN_START: 'EMAIL_SIGN_IN_START',
    SINGIN_SUCCESS: 'SIGN_IN_SUCCESS',
    SINGIN_FAILURE: 'SIGN_IN_FAILURE',
}

export default UserActionTypes;